// Assignment5/app/src/app/lobbies/page.tsx
'use client'

import React, { useEffect } from 'react';
import {useLobby, useUser} from '@/store';
import { useRouter } from 'next/navigation';
import Lobby from "@/app/components/Lobby";
import CreateLobbyModal from "@/app/components/CreateLobbyModal";

const LobbiesPage: React.FC = () => {
    const { user } = useUser();
    const {
        lobbies,
        loading,
        error,
        joinLobby,
        startLobby,
        createLobby,
    } = useLobby();
    const router = useRouter();

    useEffect(() => {
        if (!user) {
            router.push('/login');
        }
    }, [user, router]);

    return (
        <div className="min-h-screen flex flex-col items-center gap-4 justify-center bg-gray-100">
            {/* Render each lobby */}
            {loading ? (
                <p>Loading lobbies...</p>
            ) : error ? (
                <p className="text-red-600">{error}</p>
            ) : (
                lobbies.map((lobby) => (
                    <Lobby
                        key={lobby.id}
                        lobby={lobby}
                        onJoinLobby={() => joinLobby(lobby.id)}
                        onStartGame={() => startLobby(lobby.id)}
                    />
                ))
            )}

            {/* Create Lobby Modal */}
            <CreateLobbyModal onCreateLobby={createLobby} />
        </div>
    );
};

export default LobbiesPage;

// Assignment3/client/pages/lobbies.vue
<script setup lang="ts">
import { useUserStore } from '~/src/store/user.store'
import Lobby from '~/src/components/lobby/lobby.vue'
import { useLobbyStore } from '~/src/store/lobby.store'
import CreateLobbyModal from '~/src/components/lobby/create-lobby-modal.vue'

const userStore = useUserStore()
const lobbyStore = useLobbyStore()

if (!userStore.user) {
  navigateTo('/login')
}
</script>

<template>
  <div class="w-full flex flex-col items-center mt-32 gap-4">
    <lobby
      v-for="lobby in lobbyStore.lobbies"
      :lobby="lobby"
      @join-lobby="lobbyStore.joinLobby(lobby.id)"
      @start-game="lobbyStore.startLobby(lobby.id)"
      :key="lobby.id"
    />

    <create-lobby-modal />
  </div>
</template>

<style scoped></style>
