// Assignment5/app/src/app/components/Lobby.tsx
import React, { useMemo } from 'react';
import { Lobby as LobbyType } from '@/types';
import { useUser } from '@/store';

interface LobbyProps {
    lobby: LobbyType;
    onJoinLobby: () => void;
    onStartGame: () => void;
}

const Lobby: React.FC<LobbyProps> = ({ lobby, onJoinLobby, onStartGame }) => {
    const { user } = useUser();

    const hasJoined = useMemo(() => {
        return lobby.players.some((player) => player.id === user?.id);
    }, [lobby.players, user]);

    return (
        <div className="w-80 p-4 flex flex-col gap-2 bg-white rounded-lg shadow-md">
            <div className="flex justify-between">
                <h5 className="font-semibold text-gray-700">{lobby.name}</h5>
                <p className="text-sm text-gray-500">{lobby.players.length}/4</p>
            </div>

            <div>
                {lobby.players.map((player) => (
                    <div key={player.id} className="text-sm p-2 bg-slate-200 rounded-md flex justify-between items-center mb-1 text-gray-700">
                        <span>{player.name}</span>
                    </div>
                ))}
            </div>

            {!hasJoined ? (
                <button
                    onClick={onJoinLobby}
                    className="px-2 py-1 bg-blue-200 text-blue-700 rounded-md w-full hover:bg-blue-300"
                >
                    Join
                </button>
            ) : (
                lobby.players.length > 1 && (
                    <button
                        onClick={onStartGame}
                        className="px-2 py-1 bg-green-200 text-green-700 rounded-md w-full hover:bg-green-300"
                    >
                        Start Game
                    </button>
                )
            )}
        </div>
    );
};

export default Lobby;

// Assignment3/client/src/components/lobby/lobby.vue
<script setup lang="ts">
import type { Lobby } from '~/src/types/types'
import { useUserStore } from '~/src/store/user.store'

const userStore = useUserStore()
const props = defineProps<{
  lobby: Lobby
}>()

const emit = defineEmits(['join-lobby', 'start-game'])

const hasJoined = computed(() => {
  return userStore.user?.id === props.lobby.players.find((p) => p.id === userStore.user?.id)?.id
})

const handleJoinLobby = () => {
  emit('join-lobby')
}

const handleStartGame = () => {
  emit('start-game')
}
</script>

<template>
  <div class="w-80 p-4 flex flex-col gap-2 bg-white rounded-lg">
    <div class="flex justify-between">
      <h5>{{ props.lobby.name }}</h5>
      <p>{{ props.lobby.players.length }}/4</p>
    </div>

    <div v-for="p in props.lobby.players" class="text-sm p-2 bg-slate-200 rounded-md flex justify-between items-center">
      <label for="opponent">{{ p.name }}</label>
    </div>

    <button v-if="!hasJoined" class="px-2 py-1 bg-blue-200 text-blue-700 rounded-md w-full" @click="handleJoinLobby()">
      Join
    </button>
    <button
      v-if="hasJoined && props.lobby.players.length > 1"
      class="px-2 py-1 bg-blue-200 text-blue-700 rounded-md w-full"
      @click="handleStartGame"
    >
      Start game
    </button>
  </div>
</template>

<style scoped></style>
