// Assignment5/app/src/app/components/player-interface/HandCompletedModal.tsx
import React from 'react';
import {useGame} from "@/store";

const HandCompletedModal: React.FC = () => {
    const { displayHandCompleteModal, closeModal, game } = useGame();

    if (!displayHandCompleteModal || !game) {
        return null;
    }

    const players = game.players.map((playerName, i) => ({
        name: playerName,
        score: game.playerScores[i],
    }));

    return (
        <>
            <span className="absolute w-full h-full bg-slate-100 opacity-70 z-50" />
            <div
                className="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 p-4 bg-slate-100 flex flex-col justify-center items-center gap-2 z-50 rounded-md drop-shadow-2xl"
            >
                {players.map((p) => (
                    <p key={p.name}>
                        {p.name}: {p.score}
                    </p>
                ))}
                <button
                    className="bg-blue-600 px-3 py-2 text-white rounded"
                    onClick={closeModal}
                >
                    Continue
                </button>
            </div>
        </>
    );
};

export default HandCompletedModal;

// Assignment3/client/src/components/player-interface/hand-completed-modal.vue
<script setup lang="ts">
import { useGameStore } from '~/src/store/game.store'

const store = useGameStore()

const players = computed(() => {
  const players = store.game?.players

  return players?.map((player, i) => {
    return {
      name: player,
      score: store.game?.playerScores[i],
    }
  })
})
</script>

<template>
  <span v-if="store.displayHandCompleteModal" class="absolute w-full h-full bg-slate-100 opacity-70 z-50" />

  <div
    v-if="store.displayHandCompleteModal"
    class="absolute left-1/2 top-1/2 transform -translate-x-1/2 -translate-y-1/2 w-80 p-4 bg-slate-100 flex flex-col justify-center items-center gap-2 z-50 rounded-md drop-shadow-2xl"
  >
    <div v-for="p in players">
      <p>{{ p.name }}: {{ p.score }}</p>
    </div>

    <button class="bg-blue-600 px-3 py-2 text-white rounded" @click="store.closeModal()">Continue</button>
  </div>
</template>

<style scoped></style>
