// Assignment3/client/src/components/piles/discard-pile.vue
<script setup lang="ts">
import { useGameStore } from '~/src/store/game.store'
import UnoCard from '../cards/uno-card/uno-card.vue'

const store = useGameStore()

const card = computed(() => {
  const cards = store.game?.currentHand?.discardPile.cards
  return cards ? cards[cards.length - 1] : null
})
</script>

<template>
  <div class="relative w-56 h-80">
    <uno-card v-if="card" :card="card" />
  </div>
</template>

<style scoped></style>

// Assignment5/app/src/app/components/piles/DiscardPile.tsx
import React from 'react';
import {useGame} from "@/store";
import UnoCard from "@/app/components/cards/uno-card/UnoCard";

const DiscardPile: React.FC = () => {
    const { game } = useGame();

    const cards = game?.currentHand?.discardPile.cards;
    const card = cards ? cards[cards.length - 1] : null;

    if (!card) return null;

    return (
        <div className="relative w-56 h-80">
            <UnoCard card={card} />
        </div>
    );
};

export default DiscardPile;
