// Assignment3/client/pages/game/[id].vue
<script setup lang="ts">
import { useUserStore } from '~/src/store/user.store'
import Bots from '~/src/components/bot-interface/bots.vue'
import RequestedColorIndicator from '~/src/components/requested-color/requested-color-indicator.vue'
import Piles from '~/src/components/piles/piles.vue'
import PlayerInterface from '~/src/components/player-interface/player-interface.vue'
import { useGameStore } from '~/src/store/game.store'

const route = useRoute()
const gameStore = useGameStore()
const userStore = useUserStore()

if (!userStore.user) {
  navigateTo('/login')
}

gameStore.initWs(parseInt(route.params.id))
</script>

<template>
  <div>
    <h1 v-if="!gameStore.game">Waiting for other players</h1>
    <div v-if="gameStore.game">
      <player-interface />
      <bots />
      <requested-color-indicator />
      <piles />
    </div>
  </div>
</template>

<style scoped></style>

// Assignment5/app/src/app/game/[id]/page.tsx
'use client'

import React, {useEffect} from 'react';
import { useRouter, useParams } from 'next/navigation';
import { useGame, useUser } from '@/store';
import PlayerInterface from '@/app/components/player-interface/PlayerInterface';
import Bots from '@/app/components/bot-interface/Bots';
import RequestedColorIndicator from '@/app/components/requested-color/RequestedColorIndicator';
import Piles from '@/app/components/piles/Piles';

const GamePage: React.FC = () => {
    const { user } = useUser();
    const { initWs, game } = useGame();
    const router = useRouter();
    const params = useParams();
    const { id } = params;

    useEffect(() => {
        if (!user) {
            router.push('/login');
        }
    }, [user,  router]);

    useEffect(() => {
        initWs(parseInt(id as string))
    }, []);

    if (!user) {
        return null;
    }


    return (
        <div>
            {!game ? (
                <h1>Waiting for other players</h1>
            ) : (
                <div>
                    <PlayerInterface />
                    <Bots />
                    <RequestedColorIndicator />
                    <Piles />
                </div>
            )}
        </div>
    );
};

export default GamePage;
