// Assignment2/src/components/player-interface/hand.vue
<script setup lang="ts">
import { usePlayerStore } from '~/src/store/player.store'
import UnoCard from '~/src/components/cards/uno-card/uno-card.vue'

const store = usePlayerStore()
</script>

<template>
  <div
    class="absolute -bottom-40 left-1/2 -translate-x-1/2 flex -space-x-32"
    :class="!store.isPlayerInTurn && 'opacity-70'"
  >
    <uno-card
      v-for="(card, i) in store.playerCards"
      :key="i"
      :card="card"
      class="cursor-pointer transform hover:-translate-y-12 shadow-lg transition-all duration-200 ease-in-out"
      @click="store.playCard(i)"
    />
  </div>
</template>

<style scoped></style>

// Assignment5/app/src/app/components/player-interface/Hand.tsx
import React from 'react';
import {usePlayer} from "@/store";
import UnoCard from "@/app/components/cards/uno-card/UnoCard";

const Hand: React.FC = () => {
    const { playerCards, isPlayerInTurn, playCard } = usePlayer();

    if (!playerCards || playerCards.length === 0) return null;

    return (
        <div
            className={`absolute -bottom-40 left-1/2 transform -translate-x-1/2 flex -space-x-32 ${
                !isPlayerInTurn ? 'opacity-70' : ''
            }`}
        >
            {playerCards.map((card, i) => (
                <UnoCard
                    key={i}
                    card={card}
                    className={`cursor-pointer transform shadow-lg transition-all duration-200 ease-in-out ${
                        isPlayerInTurn ? 'hover:-translate-y-12' : ''
                    }`}
                    onClick={() => {
                        console.log(`Card clicked: index=${i}, card=`, card);
                        playCard(i);
                    }}
                />
            ))}
        </div>
    );
};

export default Hand;
