// Assignment3/client/src/components/player-interface/player-interface.vue
<script setup lang='ts'>
import RequestColor from '~/src/components/player-interface/request-color.vue'
import SayUno from '~/src/components/player-interface/say-uno.vue'
import Hand from '~/src/components/player-interface/hand.vue'
import HandCompletedModal from '~/src/components/player-interface/hand-completed-modal.vue'
import GameCompletedModal from '~/src/components/player-interface/game-completed-modal.vue'
</script>

<template>
  <hand/>
  <say-uno/>
  <request-color/>
  <hand-completed-modal />
  <game-completed-modal />
</template>

<style scoped>

</style>

// Assignment5/app/src/app/components/player-interface/PlayerInterface.tsx
import React from 'react';
import RequestColor from './RequestColor';
import SayUno from './SayUno';
import Hand from './Hand';
import HandCompletedModal from './HandCompletedModal';
import GameCompletedModal from './GameCompletedModal';

const PlayerInterface: React.FC = () => {
    return (
        <>
            <Hand />
            <SayUno />
            <RequestColor />
            <HandCompletedModal />
            <GameCompletedModal />
        </>
    );
};

export default PlayerInterface;
