// Assignment5/app/src/app/components/bot-interface/Bots.tsx
import React from 'react';
import BotInterface from './BotInterface';
import { POSITIONS_ARRAY } from './utils';
import {useGame, useUser} from "@/store";

const Bots: React.FC = () => {
    const { game } = useGame();
    const { user } = useUser();

    if (!game || !user) return null;

    const otherPlayers = game.players
        .map((playerName, index) => ({ name: playerName, index }))
        .filter((player) => player.name !== user.name);

    const numBots = otherPlayers.length;

    if (numBots === 0) {
        return null;
    }

    if (!POSITIONS_ARRAY[numBots]) {
        console.warn(`No position configuration for ${numBots} bots.`);
        return null;
    }

    return (
        <>
            {otherPlayers.map((player, idx) => (
                <BotInterface
                    key={`${player.index}-bot`}
                    playerIndex={player.index}
                    position={POSITIONS_ARRAY[numBots][idx]}
                />
            ))}
        </>
    );
};

export default Bots;

// Assignment3/client/src/components/bot-interface/bots.vue
<script setup lang="ts">
import { useGameStore } from '~/src/store/game.store'
import BotInterface from './bot-interface.vue'
import { POSITIONS_ARRAY } from '~/src/components/bot-interface/utils'
import { useUserStore } from '~/src/store/user.store'
const userStore = useUserStore()
const gameStore = useGameStore()

const players = computed(() => {
  const userName = userStore.user?.name
  return gameStore.game?.players.filter((player) => player !== userName)
})
</script>

<template>
  <bot-interface
    v-for="(_, index) in players"
    :key="`${index}-bot`"
    :player-index="index"
    :position="POSITIONS_ARRAY[players.length - 1][index]"
  />
</template>

<style scoped></style>
